In [81]:
import numpy as np
import pandas as pd
import psycopg2
import recordlinkage

import settings

In [82]:
conn = psycopg2.connect(database=settings.DB, user=settings.UN, password=settings.PW,
        host=settings.H, port=settings.PORT)

In [83]:
tables = pd.read_sql_query("""
SELECT table_name
  FROM information_schema.tables
 WHERE table_schema='public'
   AND table_type='BASE TABLE'
   AND table_name not like '%_old'""", conn)

In [84]:
table_names = tables['table_name'].tolist()

In [85]:
table_names

['goe',
 'pcs',
 'scraped_totals',
 'total_scores',
 'judges_with_countries',
 'calls',
 'elt_scores',
 'deductions',
 'judges',
 'competitors']

In [86]:
df_clean = pd.read_sql_query("Select * FROM competitors", conn)

In [87]:
df_clean.sort_values('name').head()

     line_id  season    disc category               name country
713      713  SB2009  Ladies       Sr  Abigail PIETERSEN     RSA
907      907  SB2017     Men       Sr  Abzal RAKIMGALIEV     KAZ
933      933  SB2011     Men       Sr        Adam RIPPON     USA
938      938  SB2012  Ladies       Sr  Adelina SOTNIKOVA     RUS
309      309  SB2010  Ladies       Jr  Adelina SOTNIKOVA     RUS

In [88]:
df = df_clean.copy()

In [89]:
df.set_index('line_id', inplace=True)

In [90]:
df['name'] = df['name'].apply(lambda x: x.lower())

In [91]:
comparison_methods = ['jaro','jarowinkler', 'levenshtein','damerau_levenshtein', 'qgram', 'cosine']

In [92]:
indexer = recordlinkage.Index()
indexer.full()
pairs = indexer.index(df)

WARNING:recordlinkage:indexing - performance warning - A full index can result in large number of record pairs.

In [24]:
for method in comparison_methods:
    compare_cl = recordlinkage.Compare()
    compare_cl.string('name', 'name', method=method, label='name_match')

    features = compare_cl.compute(pairs, df)
    
    matches = features[features.name_match >= .75]
    matches.reset_index(inplace=True)
    matches = matches[matches['line_id_1'] != matches['line_id_2']]
    
    matched = matches.merge(df, left_on='line_id_1', right_on='line_id')
    matched = matched.merge(df, left_on='line_id_2', right_on='line_id', suffixes=['_First', '_Second'])
    matched = matched[matched['disc_First'] == matched['disc_Second']]
    
    print(f"Similarity method {method}: {len(matched[matched['name_match'] != 1])} potential matches")
    print(matched[matched['name_match'] != 1].sort_values('name_match', ascending=True).head(20))

Similarity method jaro: 555 potential matches
     line_id_1  line_id_2  name_match season_First disc_First category_First  \
326        572        261    0.750000       SB2004        Men             Sr
125        425         27    0.750000       SB2006     Ladies             Sr
493        778        440    0.750000       SB2012     Ladies             Sr
407        453        113    0.750000       SB2014     Ladies             Sr
515        542        377    0.750000       SB2009        Men             Sr
561        596        190    0.750000       SB2005     Ladies             Sr
20         423         18    0.750000       SB2015        Men             Sr
18         342         18    0.750000       SB2014        Men             Jr
35         131        129    0.750318       SB2015     Ladies             Sr
207        853         90    0.750318       SB2017     Ladies             Sr
204        355         90    0.750318       SB2016     Ladies             Jr
229        632        311    0.750318       SB2006     Ladies             Sr
11          85         45    0.750318       SB2005        Men             Sr
283        479        347    0.751082       SB2017     Ladies             Sr
280        356        347    0.751082       SB2016     Ladies             Jr
728        830         24    0.751082       SB2015     Ladies             Sr
591        854        479    0.751082       SB2017     Ladies             Sr
343        854        356    0.751082       SB2017     Ladies             Sr
323        885        134    0.751178       SB2017        Men             Sr
604        672        453    0.751178       SB2008     Ladies             Sr

             name_First country_First season_Second disc_Second  \
326  andrei dobrokhodov           AZE        SB2017         Men
125            dan fang           CHN        SB2007      Ladies
493  viktoria helgesson           SWE        SB2006      Ladies
407     maria artemieva           RUS        SB2013      Ladies
515        song chol ri           PRK        SB2007         Men
561     laura fernandez           ESP        SB2005      Ladies
20     alexander petrov           RUS        SB2004         Men
18     alexander petrov           RUS        SB2004         Men
35       daniela stoeva           BUL        SB2015      Ladies
207      alina zagitova           RUS        SB2010      Ladies
204      alina zagitova           RUS        SB2010      Ladies
229   kristin wieczorek           GER        SB2010      Ladies
11    michael chrolenko           NOR        SB2004         Men
283      kaori sakamoto           JPN        SB2015      Ladies
280      kaori sakamoto           JPN        SB2015      Ladies
728      sonia lafuente           ESP        SB2017      Ladies
591      maria sotskova           RUS        SB2017      Ladies
343      maria sotskova           RUS        SB2016      Ladies
323     alexei bychenko           ISR        SB2015         Men
604  maria papasotiriou           GRE        SB2014      Ladies

    category_Second         name_Second country_Second
326              Sr        andrew dodds            AUS
125              Sr           tina wang            AUS
493              Sr  viktoria volchkova            RUS
407              Sr        marta garcia            ESP
515              Sr            song gao            CHN
561              Sr        lauren henry            RSA
20               Sr    alexander shubin            RUS
18               Sr    alexander shubin            RUS
35               Sr   danielle harrison            GBR
207              Sr   svetlana issakova            EST
204              Sr   svetlana issakova            EST
229              Jr      kristiene gong            USA
11               Sr      michal matloch            CZE
283              Jr      maria sotskova            RUS
280              Jr      maria sotskova            RUS
728              Sr      anita oestlund            SWE
591              Sr      kaori sakamoto            JPN
343              Jr      kaori sakamoto            JPN
323              Sr  alexei mialionkhin            BLR
604              Sr     maria artemieva            RUS
Similarity method jarowinkler: 1103 potential matches
      line_id_1  line_id_2  name_match season_First disc_First category_First  \
321         425         27    0.750000       SB2006     Ladies             Sr
163         678         86    0.750000       SB2008        Men             Sr
1413        839        510    0.750000       SB2016     Ladies             Sr
1008        831        467    0.750000       SB2015        Men             Sr
470         355         90    0.750318       SB2016     Ladies             Jr
473         853         90    0.750318       SB2017     Ladies             Sr
509         843        311    0.750549       SB2016     Ladies             Sr
1567        843        829    0.750549       SB2016     Ladies             Sr
1299        854        479    0.751082       SB2017     Ladies             Sr
774         830         24    0.751082       SB2015     Ladies             Sr
652         356        347    0.751082       SB2016     Ladies             Jr
658         479        347    0.751082       SB2017     Ladies             Sr
785         854        356    0.751082       SB2017     Ladies             Sr
494         794        271    0.751471       SB2013     Ladies             Sr
1692        966        671    0.751961       SB2016     Ladies             Sr
529         779        309    0.752053       SB2012     Ladies             Sr
1636        897        417    0.752053       SB2017        Men             Sr
1662        938        779    0.752053       SB2012     Ladies             Sr
208         289        160    0.752110       SB2017     Ladies             Sr
337         809          5    0.752110       SB2014     Ladies             Sr

              name_First country_First season_Second disc_Second  \
321             dan fang           CHN        SB2007      Ladies
163         andrei lutai           RUS        SB2005         Men
1413           shuran yu           SGP        SB2008      Ladies
1008        ivan righini           ITA        SB2008         Men
470       alina zagitova           RUS        SB2010      Ladies
473       alina zagitova           RUS        SB2010      Ladies
509        kerstin frank           AUT        SB2010      Ladies
1567       kerstin frank           AUT        SB2015      Ladies
1299      maria sotskova           RUS        SB2017      Ladies
774       sonia lafuente           ESP        SB2017      Ladies
652       kaori sakamoto           JPN        SB2015      Ladies
658       kaori sakamoto           JPN        SB2015      Ladies
785       maria sotskova           RUS        SB2016      Ladies
494         anita madsen           DEN        SB2011      Ladies
1692   gabrielle daleman           CAN        SB2008      Ladies
529   monika simancikova           SVK        SB2010      Ladies
1636  julian zhi jie yee           MAS        SB2010         Men
1662   adelina sotnikova           RUS        SB2012      Ladies
208          amber glenn           USA        SB2017      Ladies
337          hae jin kim           KOR        SB2008      Ladies

     category_Second         name_Second country_Second
321               Sr           tina wang            AUS
163               Sr        adrian matei            ROM
1413              Jr        susana cantu            MEX
1008              Sr        ian martinez            CAN
470               Sr   svetlana issakova            EST
473               Sr   svetlana issakova            EST
509               Jr      kristiene gong            USA
1567              Sr      kristen spours            GBR
1299              Sr      kaori sakamoto            JPN
774               Sr      anita oestlund            SWE
652               Jr      maria sotskova            RUS
658               Jr      maria sotskova            RUS
785               Jr      kaori sakamoto            JPN
494               Sr   adriana desanctis            CAN
1692              Sr     isabelle pieman            BEL
529               Jr   adelina sotnikova            RUS
1636              Jr   ryan zhi jwen yee            MAS
1662              Sr  monika simancikova            SVK
208               Sr      aimee buchanan            ISR
337               Sr      hyeon-jung kim            KOR

Similarity method levenshtein: 45 potential matches
     line_id_1  line_id_2  name_match season_First disc_First category_First  \
69         662        276    0.750000       SB2008     Ladies             Sr
95         797        765    0.750000       SB2013        Men             Sr
51         962        193    0.750000       SB2014        Men             Sr
50         523        193    0.750000       SB2008        Men             Jr
71         672        635    0.750000       SB2008     Ladies             Sr
96         908        765    0.750000       SB2017        Men             Sr
118        888        423    0.764706       SB2017        Men             Sr
9          360         18    0.764706       SB2016        Men             Jr
10         424         18    0.764706       SB2017        Men             Sr
22         888        342    0.764706       SB2017        Men             Sr
67         655        238    0.769231       SB2006        Men             Sr
123        899        775    0.777778       SB2017        Men             Sr
53         530        315    0.777778       SB2008        Men             Jr
129        937        530    0.777778       SB2011        Men             Sr
14         364        330    0.777778       SB2017     Ladies             Jr
73         681        619    0.785714       SB2008        Men             Sr
31         465         40    0.785714       SB2017        Men             Sr
61         578        547    0.789474       SB2004        Men             Sr
46         508        364    0.823529       SB2008     Ladies             Jr
12         364         88    0.823529       SB2017     Ladies             Jr

             name_First country_First season_Second disc_Second  \
69         na-young kim           KOR        SB2016      Ladies
95          jin seo kim           KOR        SB2010         Men
51             nan song           CHN        SB2005         Men
50             nan song           CHN        SB2005         Men
71   maria papasotiriou           GRE        SB2006      Ladies
96           jinseo kim           KOR        SB2010         Men
118   alexander majorov           SWE        SB2015         Men
9     alexander samarin           RUS        SB2004         Men
10    alexander samarin           RUS        SB2004         Men
22    alexander majorov           SWE        SB2014         Men
67        dong-whun lee           KOR        SB2013         Men
123  slavik hayrapetyan           ARM        SB2010         Men
53            jean bush           RUS        SB2010         Men
129           zhan bush           RUS        SB2008         Men
14    alexandra trusova           RUS        SB2013      Ladies
73        igor macypura           SVK        SB2005         Men
31       andrei lazukin           RUS        SB2004         Men
61     evgeni plushenko           RUS        SB2013         Men
46     alexandra kunova           SVK        SB2017      Ladies
12    alexandra trusova           RUS        SB2010      Ladies

    category_Second               name_Second country_Second
69               Sr                nahyun kim            KOR
95               Sr              min-seok kim            KOR
51               Sr                  lun song            CHN
50               Sr                  lun song            CHN
71               Sr  maria-elena papasotiriou            GRE
96               Sr              min-seok kim            KOR
118              Sr          alexander petrov            RUS
9                Sr          alexander shubin            RUS
10               Sr          alexander shubin            RUS
22               Jr          alexander petrov            RUS
67               Sr              dong won lee            KOR
123              Sr        sarkis hayrapetyan            ARM
53               Jr                 zhan bush            RUS
129              Jr                 jean bush            RUS
14               Jr        alexandra proklova            RUS
73               Sr            igor matsipura            SVK
31               Sr              andrei lezin            RUS
61               Sr       evgeny plyushchenko            RUS
46               Jr         alexandra trusova            RUS
12               Sr          alexandra kunova            SVK
Similarity method damerau_levenshtein: 45 potential matches
     line_id_1  line_id_2  name_match season_First disc_First category_First  \
69         662        276    0.750000       SB2008     Ladies             Sr
51         962        193    0.750000       SB2014        Men             Sr
50         523        193    0.750000       SB2008        Men             Jr
71         672        635    0.750000       SB2008     Ladies             Sr
95         797        765    0.750000       SB2013        Men             Sr
96         908        765    0.750000       SB2017        Men             Sr
9          360         18    0.764706       SB2016        Men             Jr
10         424         18    0.764706       SB2017        Men             Sr
22         888        342    0.764706       SB2017        Men             Sr
118        888        423    0.764706       SB2017        Men             Sr
67         655        238    0.769231       SB2006        Men             Sr
14         364        330    0.777778       SB2017     Ladies             Jr
53         530        315    0.777778       SB2008        Men             Jr
123        899        775    0.777778       SB2017        Men             Sr
129        937        530    0.777778       SB2011        Men             Sr
73         681        619    0.785714       SB2008        Men             Sr
31         465         40    0.785714       SB2017        Men             Sr
61         578        547    0.789474       SB2004        Men             Sr
46         508        364    0.823529       SB2008     Ladies             Jr
12         364         88    0.823529       SB2017     Ladies             Jr

             name_First country_First season_Second disc_Second  \
69         na-young kim           KOR        SB2016      Ladies
51             nan song           CHN        SB2005         Men
50             nan song           CHN        SB2005         Men
71   maria papasotiriou           GRE        SB2006      Ladies
95          jin seo kim           KOR        SB2010         Men
96           jinseo kim           KOR        SB2010         Men
9     alexander samarin           RUS        SB2004         Men
10    alexander samarin           RUS        SB2004         Men
22    alexander majorov           SWE        SB2014         Men
118   alexander majorov           SWE        SB2015         Men
67        dong-whun lee           KOR        SB2013         Men
14    alexandra trusova           RUS        SB2013      Ladies
53            jean bush           RUS        SB2010         Men
123  slavik hayrapetyan           ARM        SB2010         Men
129           zhan bush           RUS        SB2008         Men
73        igor macypura           SVK        SB2005         Men
31       andrei lazukin           RUS        SB2004         Men
61     evgeni plushenko           RUS        SB2013         Men
46     alexandra kunova           SVK        SB2017      Ladies
12    alexandra trusova           RUS        SB2010      Ladies

    category_Second               name_Second country_Second
69               Sr                nahyun kim            KOR
51               Sr                  lun song            CHN
50               Sr                  lun song            CHN
71               Sr  maria-elena papasotiriou            GRE
95               Sr              min-seok kim            KOR
96               Sr              min-seok kim            KOR
9                Sr          alexander shubin            RUS
10               Sr          alexander shubin            RUS
22               Jr          alexander petrov            RUS
118              Sr          alexander petrov            RUS
67               Sr              dong won lee            KOR
14               Jr        alexandra proklova            RUS
53               Jr                 zhan bush            RUS
123              Sr        sarkis hayrapetyan            ARM
129              Jr                 jean bush            RUS
73               Sr            igor matsipura            SVK
31               Sr              andrei lezin            RUS
61               Sr       evgeny plyushchenko            RUS
46               Jr         alexandra trusova            RUS
12               Sr          alexandra kunova            SVK

Similarity method qgram: 24 potential matches
     line_id_1  line_id_2  name_match season_First disc_First category_First  \
53         672        635    0.760000       SB2008     Ladies             Sr
73         787        546    0.777778       SB2013     Ladies             Sr
45         546        317    0.777778       SB2013     Ladies             Sr
1          223        219    0.785714       SB2011     Ladies             Sr
108        940        550    0.800000       SB2012     Ladies             Sr
66         751        695    0.800000       SB2010     Ladies             Sr
68         777        692    0.800000       SB2012     Ladies             Sr
3          276        246    0.833333       SB2016     Ladies             Sr
102        908        797    0.833333       SB2017        Men             Sr
79         809        543    0.833333       SB2014     Ladies             Sr
91         867        824    0.833333       SB2017     Ladies             Sr
81         825        438    0.846154       SB2015     Ladies             Sr
5          362         25    0.846154       SB2016        Men             Jr
4          278         25    0.846154       SB2017        Men             Sr
40         511        100    0.846154       SB2008     Ladies             Jr
92         874         24    0.866667       SB2017     Ladies             Sr
69         781        403    0.882353       SB2012     Ladies             Sr
101        901        849    0.904762       SB2017        Men             Sr
88         901        456    0.904762       SB2017        Men             Sr
110        950        421    0.913043       SB2014     Ladies             Sr

                 name_First country_First season_Second disc_Second  \
53       maria papasotiriou           GRE        SB2006      Ladies
73        julia lipnitskaia           RUS        SB2013      Ladies
45        yulia lipnitskaya           RUS        SB2011      Ladies
1             sandra kohpon           THA        SB2011      Ladies
108               mao asada           JPN        SB2007      Ladies
66           min-jeong kwak           KOR        SB2009      Ladies
68                 yuna kim           KOR        SB2009      Ladies
3                nahyun kim           KOR        SB2015      Ladies
102              jinseo kim           KOR        SB2013         Men
79              hae jin kim           KOR        SB2013      Ladies
91               dabin choi           KOR        SB2015      Ladies
81             so youn park           KOR        SB2017      Ladies
5              jun hwan cha           KOR        SB2017         Men
4              jun hwan cha           KOR        SB2017         Men
40             romy buehler           SUI        SB2011      Ladies
92            anita östlund           SWE        SB2017      Ladies
69         tina stuerzinger           SUI        SB2010      Ladies
101    morisi kvitelashvili           GEO        SB2016         Men
88     morisi kvitelashvili           GEO        SB2014         Men
110  elizaveta tuktamysheva           RUS        SB2011      Ladies

    category_Second               name_Second country_Second
53               Sr  maria-elena papasotiriou            GRE
73               Sr         yulia lipnitskaya            RUS
45               Jr         julia lipnitskaia            RUS
1                Sr             sandra khopon            THA
108              Sr                 mai asada            JPN
66               Sr             min-jung kwak            KOR
68               Sr                 yu-na kim            KOR
3                Sr               na hyun kim            KOR
102              Sr               jin seo kim            KOR
79               Sr                haejin kim            KOR
91               Sr               da bin choi            KOR
81               Sr               soyoun park            KOR
5                Sr               junhwan cha            KOR
4                Sr               junhwan cha            KOR
40               Sr               romy bühler            SUI
92               Sr            anita oestlund            SWE
69               Jr           tina stürzinger            SUI
101              Sr       moris kvitelashvili            GEO
88               Sr       moris kvitelashvili            RUS
110              Sr    elizaveta tuktamisheva            RUS
Similarity method cosine: 91 potential matches
     line_id_1  line_id_2  name_match season_First disc_First category_First  \
45         508        330    0.750939       SB2008     Ladies             Jr
9          330         88    0.750939       SB2013     Ladies             Jr
63         681        619    0.759072       SB2008        Men             Sr
76         756         26    0.768706       SB2010     Ladies             Sr
46         508        364    0.769484       SB2008     Ladies             Jr
10         364         88    0.769484       SB2017     Ladies             Jr
4          777        246    0.769800       SB2012     Ladies             Sr
55         578        547    0.782586       SB2004        Men             Sr
23         425         16    0.783349       SB2006     Ladies             Sr
1          223        219    0.785714       SB2011     Ladies             Sr
119        940        550    0.800000       SB2012     Ladies             Sr
14         366        357    0.801193       SB2017     Ladies             Jr
84         787        546    0.826869       SB2013     Ladies             Sr
52         546        317    0.826869       SB2013     Ladies             Sr
75         751        695    0.828079       SB2010     Ladies             Sr
79         777        692    0.843274       SB2012     Ladies             Sr
78         773        216    0.861640       SB2010        Men             Sr
90         809        543    0.870388       SB2014     Ladies             Sr
3          276        246    0.870388       SB2016     Ladies             Sr
102        867        824    0.870388       SB2017     Ladies             Sr

               name_First country_First season_Second disc_Second  \
45       alexandra kunova           SVK        SB2013      Ladies
9      alexandra proklova           RUS        SB2010      Ladies
63          igor macypura           SVK        SB2005         Men
76           melinda wang           TPE        SB2007      Ladies
46       alexandra kunova           SVK        SB2017      Ladies
10      alexandra trusova           RUS        SB2010      Ladies
4                yuna kim           KOR        SB2015      Ladies
55       evgeni plushenko           RUS        SB2013         Men
23               dan fang           CHN        SB2004      Ladies
1           sandra kohpon           THA        SB2011      Ladies
119             mao asada           JPN        SB2007      Ladies
14   anastasia tarakanova           RUS        SB2016      Ladies
84      julia lipnitskaia           RUS        SB2013      Ladies
52      yulia lipnitskaya           RUS        SB2011      Ladies
75         min-jeong kwak           KOR        SB2009      Ladies
79               yuna kim           KOR        SB2009      Ladies
78      harry hau yin lee           HKG        SB2009         Men
90            hae jin kim           KOR        SB2013      Ladies
3              nahyun kim           KOR        SB2015      Ladies
102            dabin choi           KOR        SB2015      Ladies

    category_Second            name_Second country_Second
45               Jr     alexandra proklova            RUS
9                Sr       alexandra kunova            SVK
63               Sr         igor matsipura            SVK
76               Sr  melinda sherilyn wang            TPE
46               Jr      alexandra trusova            RUS
10               Sr       alexandra kunova            SVK
4                Sr            na hyun kim            KOR
55               Sr    evgeny plyushchenko            RUS
23               Sr              fan zhang            CHN
1                Sr          sandra khopon            THA
119              Sr              mai asada            JPN
14               Jr    anastasiia gubanova            RUS
84               Sr      yulia lipnitskaya            RUS
52               Jr      julia lipnitskaia            RUS
75               Sr          min-jung kwak            KOR
79               Sr              yu-na kim            KOR
78               Sr            hau yin lee            HKG
90               Sr             haejin kim            KOR
3                Sr            na hyun kim            KOR
102              Sr            da bin choi            KOR

In [93]:
compare_cl = recordlinkage.Compare()
compare_cl.string('name', 'name', method='cosine', label='name_match')

features = compare_cl.compute(pairs, df)

In [94]:
matches = features[features.name_match >= .75]
matches.reset_index(inplace=True)
matches = matches[matches['line_id_1'] != matches['line_id_2']]

In [95]:
matched = matches.merge(df, left_on='line_id_1', right_on='line_id')
matched = matched.merge(df, left_on='line_id_2', right_on='line_id', suffixes=['_First', '_Second'])
matched = matched[(matched['disc_First'] == matched['disc_Second'])]

In [96]:
matched[matched['name_match'] != 1].sort_values('name_match', ascending=True).head(30)

,line_id_1,line_id_2,name_match,season_First,disc_First,category_First,name_First,country_First,season_Second,disc_Second,category_Second,name_Second,country_Second
45,508,330,0.750939,SB2008,Ladies,Jr,alexandra kunova,SVK,SB2013,Ladies,Jr,alexandra proklova,RUS
9,330,88,0.750939,SB2013,Ladies,Jr,alexandra proklova,RUS,SB2010,Ladies,Sr,alexandra kunova,SVK
63,681,619,0.759072,SB2008,Men,Sr,igor macypura,SVK,SB2005,Men,Sr,igor matsipura,SVK
76,756,26,0.768706,SB2010,Ladies,Sr,melinda wang,TPE,SB2007,Ladies,Sr,melinda sherilyn wang,TPE
46,508,364,0.769484,SB2008,Ladies,Jr,alexandra kunova,SVK,SB2017,Ladies,Jr,alexandra trusova,RUS
10,364,88,0.769484,SB2017,Ladies,Jr,alexandra trusova,RUS,SB2010,Ladies,Sr,alexandra kunova,SVK
4,777,246,0.769800,SB2012,Ladies,Sr,yuna kim,KOR,SB2015,Ladies,Sr,na hyun kim,KOR
55,578,547,0.782586,SB2004,Men,Sr,evgeni plushenko,RUS,SB2013,Men,Sr,evgeny plyushchenko,RUS
23,425,16,0.783349,SB2006,Ladies,Sr,dan fang,CHN,SB2004,Ladies,Sr,fan zhang,CHN
1,223,219,0.785714,SB2011,Ladies,Sr,sandra kohpon,THA,SB2011,Ladies,Sr,sandra khopon,THA
119,940,550,0.800000,SB2012,Ladies,Sr,mao asada,JPN,SB2007,Ladies,Sr,mai asada,JPN
14,366,357,0.801193,SB2017,Ladies,Jr,anastasia tarakanova,RUS,SB2016,Ladies,Jr,anastasiia gubanova,RUS
84,787,546,0.826869,SB2013,Ladies,Sr,julia lipnitskaia,RUS,SB2013,Ladies,Sr,yulia lipnitskaya,RUS
52,546,317,0.826869,SB2013,Ladies,Sr,yulia lipnitskaya,RUS,SB2011,Ladies,Jr,julia lipnitskaia,RUS
75,751,695,0.828079,SB2010,Ladies,Sr,min-jeong kwak,KOR,SB2009,Ladies,Sr,min-jung kwak,KOR
79,777,692,0.843274,SB2012,Ladies,Sr,yuna kim,KOR,SB2009,Ladies,Sr,yu-na kim,KOR
78,773,216,0.861640,SB2010,Men,Sr,harry hau yin lee,HKG,SB2009,Men,Sr,hau yin lee,HKG
90,809,543,0.870388,SB2014,Ladies,Sr,hae jin kim,KOR,SB2013,Ladies,Sr,haejin kim,KOR
3,276,246,0.870388,SB2016,Ladies,Sr,nahyun kim,KOR,SB2015,Ladies,Sr,na hyun kim,KOR
102,867,824,0.870388,SB2017,Ladies,Sr,dabin choi,KOR,SB2015,Ladies,Sr,da bin choi,KOR
113,908,797,0.870388,SB2017,Men,Sr,jinseo kim,KOR,SB2013,Men,Sr,jin seo kim,KOR
92,825,438,0.880705,SB2015,Ladies,Sr,so youn park,KOR,SB2017,Ladies,Sr,soyoun park,KOR
47,511,100,0.880705,SB2008,Ladies,Jr,romy buehler,SUI,SB2011,Ladies,Sr,romy bühler,SUI
61,672,635,0.890564,SB2008,Ladies,Sr,maria papasotiriou,GRE,SB2006,Ladies,Sr,maria-elena papasotiriou,GRE
6,362,25,0.894427,SB2016,Men,Jr,jun hwan cha,KOR,SB2017,Men,Sr,junhwan cha,KOR
5,278,25,0.894427,SB2017,Men,Sr,jun hwan cha,KOR,SB2017,Men,Sr,junhwan cha,KOR
103,874,24,0.897085,SB2017,Ladies,Sr,anita östlund,SWE,SB2017,Ladies,Sr,anita oestlund,SWE
80,781,403,0.925820,SB2012,Ladies,Sr,tina stuerzinger,SUI,SB2010,Ladies,Jr,tina stürzinger,SUI
20,950,310,0.925926,SB2014,Ladies,Sr,elizaveta tuktamysheva,RUS,SB2010,Ladies,Jr,elizaveta tuktamisheva,RUS
121,950,421,0.925926,SB2014,Ladies,Sr,elizaveta tuktamysheva,RUS,SB2011,Ladies,Sr,elizaveta tuktamisheva,RUS

In [97]:
matched[matched['name_match'] != 1].describe()

        line_id_1   line_id_2  name_match
count   91.000000   91.000000   91.000000
mean   690.571429  355.076923    0.943330
std    219.870626  185.784656    0.083332
min    223.000000   16.000000    0.750939
25%    506.500000  279.000000    0.885634
50%    756.000000  336.000000    1.000000
75%    891.500000  498.500000    1.000000
max    985.000000  849.000000    1.000000

In [117]:
d = {}
check = 0

for index, row in matched.iterrows():
    if not d:
        d[row['line_id_1']] = []
        d[row['line_id_1']].append(row['line_id_1'])
        d[row['line_id_1']].append(row['line_id_2'])
    else:
        for key in d.keys():
            if row['line_id_1'] in d[key]:
                if row['line_id_2'] in d[key]:
                    check = 1
                else:
                    d[key].append(row['line_id_2'])
                    check = 1
            elif row['line_id_2'] in d[key]:
                if row['line_id_1'] in d[key]:
                    check = 1
                else:
                    d[key].append(row['line_id_1'])
                    check = 1
        if check != 1:
            d[row['line_id_1']] = []
            d[row['line_id_1']].append(row['line_id_1'])
            d[row['line_id_1']].append(row['line_id_2'])
        check = 0

In [99]:
id_pair = {}
for key in d.keys():
    for line_id in d[key]:
        id_pair[line_id] = key

In [100]:
id_pair_df = pd.DataFrame(pd.Series(id_pair))
id_pair_df.reset_index(inplace=True)
id_pair_df.rename(columns={'index': 'line_id', 0: 'master_competitor_id'}, inplace=True)

In [101]:
df_final = df_clean.merge(id_pair_df, on='line_id', how='outer')

In [102]:
df_final['master_competitor_id'] = df_final.apply(lambda x: int(x['line_id']) if np.isnan(x['master_competitor_id']) 
                                                 else int(x['master_competitor_id']), axis=1)

In [103]:
df_final = df_final.merge(df_final[['line_id', 'name']], left_on='master_competitor_id', right_on='line_id', suffixes=['', 'x'])

In [104]:
df_final.drop('line_idx', axis=1, inplace=True)
df_final.rename(columns={'namex': 'master_competitor_name'}, inplace=True)

In [108]:
df_final[df_final['name'] != df_final['master_competitor_name']]

,line_id,season,disc,category,name,country,master_competitor_id,master_competitor_name
4,4,SB2007,Men,Sr,Robert MCNAMARA,AUS,195,Robert McNAMARA
17,16,SB2004,Ladies,Sr,Fan ZHANG,CHN,425,Dan FANG
26,24,SB2017,Ladies,Sr,Anita OESTLUND,SWE,874,Anita ÖSTLUND
28,25,SB2017,Men,Sr,Junhwan CHA,KOR,278,Jun Hwan CHA
31,26,SB2007,Ladies,Sr,Melinda Sherilyn WANG,TPE,756,Melinda WANG
43,37,SB2004,Ladies,Sr,Jaqueline BELENYESIOVA,SVK,587,Jacqueline BELENYESIOVA
100,88,SB2010,Ladies,Sr,Alexandra KUNOVA,SVK,330,Alexandra PROKLOVA
102,364,SB2017,Ladies,Jr,Alexandra TRUSOVA,RUS,330,Alexandra PROKLOVA
103,508,SB2008,Ladies,Jr,Alexandra KUNOVA,SVK,330,Alexandra PROKLOVA
116,100,SB2011,Ladies,Sr,Romy BÜHLER,SUI,511,Romy BUEHLER
219,199,SB2006,Ladies,Sr,Michele CANTU,MEX,601,Michelle CANTU
238,216,SB2009,Men,Sr,Hau Yin LEE,HKG,773,Harry Hau Yin LEE
242,219,SB2011,Ladies,Sr,Sandra KHOPON,THA,223,Sandra KOHPON
269,246,SB2015,Ladies,Sr,Na Hyun KIM,KOR,276,Nahyun KIM
271,692,SB2009,Ladies,Sr,Yu-Na KIM,KOR,276,Nahyun KIM
272,777,SB2012,Ladies,Sr,Yuna KIM,KOR,276,Nahyun KIM
348,950,SB2014,Ladies,Sr,Elizaveta TUKTAMYSHEVA,RUS,421,Elizaveta TUKTAMISHEVA
360,317,SB2011,Ladies,Jr,Julia LIPNITSKAIA,RUS,546,Yulia LIPNITSKAYA
362,787,SB2013,Ladies,Sr,Julia LIPNITSKAIA,RUS,546,Yulia LIPNITSKAYA
432,357,SB2016,Ladies,Jr,Anastasiia GUBANOVA,RUS,366,Anastasia TARAKANOVA
461,386,SB2010,Ladies,Jr,Lenaelle GILLERON-GORY,FRA,943,Lenaelle GILLERON-GORRY
480,403,SB2010,Ladies,Jr,Tina STÜRZINGER,SUI,781,Tina STUERZINGER
517,438,SB2017,Ladies,Sr,Soyoun PARK,KOR,825,So Youn PARK
536,901,SB2017,Men,Sr,Morisi KVITELASHVILI,GEO,849,Moris KVITELASHVILI
616,543,SB2013,Ladies,Sr,Haejin KIM,KOR,809,Hae Jin KIM
620,547,SB2013,Men,Sr,Evgeny PLYUSHCHENKO,RUS,578,Evgeni PLUSHENKO
624,550,SB2007,Ladies,Sr,Mai ASADA,JPN,940,Mao ASADA
642,567,SB2004,Ladies,Sr,Jenna McCORKELL,GBR,789,Jenna MCCORKELL
695,619,SB2005,Men,Sr,Igor MATSIPURA,SVK,681,Igor MACYPURA
701,624,SB2006,Ladies,Sr,Susanna POYKIO,FIN,661,Susanna PÖYKIÖ
713,635,SB2006,Ladies,Sr,Maria-Elena PAPASOTIRIOU,GRE,672,Maria PAPASOTIRIOU
737,659,SB2008,Ladies,Sr,Laura LEPISTÖ,FIN,691,Laura LEPISTO
767,695,SB2009,Ladies,Sr,Min-Jung KWAK,KOR,751,Min-Jeong KWAK
848,797,SB2013,Men,Sr,Jin Seo KIM,KOR,908,Jinseo KIM
871,824,SB2015,Ladies,Sr,Da Bin CHOI,KOR,867,Dabin CHOI

In [116]:
matched[['line_id_1', 'line_id_2']].groupby('line_id_1').count().sort_values('line_id_2', ascending=False)

           line_id_2
line_id_1
508                3
362                2
787                2
950                2
777                2
901                2
833                1
834                1
836                1
848                1
849                1
195                1
853                1
825                1
854                1
867                1
874                1
878                1
832                1
809                1
817                1
883                1
807                1
801                1
799                1
789                1
788                1
785                1
784                1
783                1
...              ...
739                1
733                1
729                1
723                1
716                1
706                1
696                1
691                1
681                1
673                1
672                1
669                1
661                1
652                1
601                1
587                1
578                1
573                1
546                1
540                1
529                1
519                1
514                1
511                1
505                1
492                1
487                1
485                1
484                1
985                1

[134 rows x 1 columns]